// Optional DOM checks: npm install --prefix .local/dashboard-qa jsdom@26.1.0 --no-save
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('../.local/dashboard-qa/node_modules/jsdom');
const html=fs.readFileSync('index.html','utf8');
function boot(query='') {
  const dom=new JSDOM(html,{url:'https://app.aivida.tech/'+query,runScripts:'outside-only'}),w=dom.window;
  w.setInterval=()=>0;
  w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
  w.HTMLDialogElement.prototype.close=function(){this.open=false;};
  const liveNodes=[...w.document.querySelectorAll('[id^="home-"]')];
  for(const script of ['news-badge','dashboard','navigation'])w.eval(fs.readFileSync('assets/'+script+'.js','utf8'));
  for(const node of liveNodes)assert.equal(w.document.getElementById(node.id),node,'collector node identity '+node.id);
  return dom;
}
const dom=boot(),w=dom.window,d=w.document;
try {
  const dashboard=d.getElementById('kb-dashboard'),grid=d.querySelector('main > .grid');
  assert.equal(dashboard.hidden,false);assert.equal(grid.hidden,true);
  assert.ok(d.body.classList.contains('kb-navigation-ready'));
  assert.equal(d.getElementById('dashboard-attention-title'),null);
  assert.equal(d.getElementById('dashboard-claims-title'),null);
  assert.ok(d.getElementById('dashboard-branches-title'));
  assert.ok(d.getElementById('dashboard-requests-title'));
  const select=id=>d.querySelector('#kb-navigation [data-kb-category="'+id+'"]').click();
  select('all');assert.equal(dashboard.hidden,true);assert.equal(grid.hidden,false);assert.equal(w.location.search,'?category=all');
  d.querySelector('[data-kb-view="cards"]').click();assert.equal(grid.classList.contains('kb-list-view'),false);
  select('dashboard');assert.equal(dashboard.hidden,false);
  const input=d.getElementById('kb-home-search');input.value='손익';input.dispatchEvent(new w.Event('input'));
  assert.equal(dashboard.hidden,true);assert.equal(grid.querySelectorAll('article:not([hidden])').length,1);
  assert.equal(grid.querySelector('article:not([hidden])').dataset.kbFeature,'operating-costs');
  select('dashboard');assert.equal(input.value,'');assert.equal(w.location.search,'');
  select('all');d.querySelector('[data-kb-pin="payroll"]').click();select('dashboard');
  assert.equal(d.querySelector('.kb-shortcut-section').hidden,false);
  assert.ok(d.querySelector('.kb-shortcuts').textContent.includes('급여'));
  const comp=w.NewsBadge.create('competitor',{}),agency=w.NewsBadge.create('agency',{});
  comp.update(['a','b']);agency.update(['c']);
  w.HomeDashboard.update('competitor',{total:2,updated_at:'2026-09-22'},{});
  w.HomeDashboard.update('agency',{total:1,support:{active:1},sources:[{id:'bizinfo',last_success:'2026-09-22'}]},{});
  assert.match(d.querySelector('[data-dash-key="metric-news"]').textContent,/3건/);
  assert.equal(w.localStorage.getItem('vida-news-seen-v1:competitor'),null,'dashboard must not mark news read');
  const anchor=d.querySelector('[data-dash-key="metric-news"]');anchor.focus();
  w.HomeDashboard.fail('agency');
  assert.equal(d.activeElement.dataset.dashKey,'metric-news','focus survives refresh');
  assert.match(d.querySelector('[data-dash-key="metric-news"]').textContent,/—/);
  assert.match(d.querySelector('[data-dash-slot="news"]').textContent,/연결 확인 필요/);
  w.HomeDashboard.update('agency',{support:{active:1},sources:[{id:'bizinfo',last_success:'2026-09-22'}]});
  assert.match(d.querySelector('[data-dash-key="metric-news"]').textContent,/3건/);
  const claims={benefitMonth:'2026-08',deadline:'2026-09-10',branches:['anyang','incheon'].map((id,i)=>({id,name:id,status:'accepted',label:'접수 완료',message:'필수 청구 접수 완료',checkedAt:'2026-09-10T13:52:10+09:00',lastQueryFailureAt:'2026-09-10T20:04:28+09:00',laborCost:{status:'verified',annualRatio:i?'68.7':'63.7',assessment:'stable',year:2026,benefitMonth:'2026-07',benchmarkRatio:'62.5',checkedAt:'2026-09-20T23:41:00+09:00'}}))};
  w.HomeDashboard.update('claims',claims);
  assert.match(d.querySelector('[data-dash-key="metric-claims"]').textContent,/2 \/ 2지점/);
  assert.equal(d.querySelector('[data-dash-key="metric-claims"]').hasAttribute('data-warning'),false);
  assert.equal(d.querySelectorAll('.dash-branch-table [data-status="warning"]').length,0);
  assert.doesNotMatch(d.querySelector('[data-dash-slot="branches"]').textContent,/재조회 실패/);
  assert.match(d.querySelector('[data-dash-slot="branches"]').textContent,/조회.*9\. 10\./,'verified timestamps stay visible');
  assert.deepEqual([...d.querySelectorAll('.dash-labor-value strong')].map(el=>el.textContent),['63.7%','68.7%']);
  assert.match(d.querySelector('[data-dash-slot="branches"]').textContent,/2026-07 조회분/);
  assert.ok(claims.branches.every(branch=>branch.lastQueryFailureAt),'failure history is not removed from data');
  w.HomeDashboard.fail('claims');
  assert.match(d.querySelector('[data-dash-slot="branches"] .dash-warning').textContent,/연결 확인 필요.*이전 조회 결과/);
  assert.equal(d.querySelectorAll('.dash-branch-table [data-status="warning"]').length,0,'connection failures do not relabel accepted branches');
  w.HomeDashboard.update('claims',claims);
  assert.equal(d.querySelector('[data-dash-slot="branches"] .dash-warning'),null);
  w.HomeDashboard.update('claims',{benefitMonth:'2026-08',deadline:'2026-09-10',branches:[{id:'x',name:'<img src=x onerror=alert(1)>',status:'check',label:'확인',message:'<script>alert(1)</script>'}]});
  assert.equal(dashboard.querySelectorAll('img,script').length,0,'untrusted data stays text');
  assert.ok(d.querySelector('.dash-branch-table [data-status="warning"]'),'unaccepted branch still needs attention');
  const requestSlot=d.querySelector('[data-dash-slot="requests"]');
  assert.doesNotMatch(requestSlot.textContent,/0건/,'loading is not zero');
  w.HomeDashboard.update('requests',null,{locked:true});
  assert.match(requestSlot.textContent,/담당자 로그인 필요/);
  const totals={counts:{new:2,contacted:1,completed:3,archived:0},kinds:{visit:2,trial:3,pricing:1},total:6,generatedAt:'2026-09-22T10:00:00+09:00',lastReceivedAt:'2026-09-21T09:00:00+09:00'};
  w.HomeDashboard.update('requests',totals);
  assert.deepEqual([...requestSlot.querySelectorAll('dd')].map(el=>el.textContent),['2건','1건','3건','0건']);
  assert.match(requestSlot.textContent,/운영 사이트 접수 기준 · 개발 사이트 제외/);
  w.HomeDashboard.fail('requests');
  assert.equal(requestSlot.querySelectorAll('dd').length,0,'private totals disappear on fetch failure');
  w.HomeDashboard.update('requests',totals);
  w.HomeDashboard.update('requests',null,{locked:true});
  assert.equal(requestSlot.querySelectorAll('dd').length,0,'private totals disappear on logout');
  w.HomeDashboard.update('requests',{...totals,total:0,lastReceivedAt:null,counts:{new:0,contacted:0,completed:0,archived:0},kinds:{visit:0,trial:0,pricing:0}});
  assert.match(requestSlot.textContent,/아직 운영 사이트에서 접수된 신청이 없습니다/);
  select('all');assert.equal(grid.classList.contains('kb-list-view'),false,'saved view survives dashboard');
  console.log('PASS: dashboard sections, branch/labor status, authenticated totals, live nodes, navigation, error/recovery, focus, escaping and unread preservation');
} finally {dom.window.close();}
for(const [query,isDashboard] of [['?category=all',false],['?category=operations',false],['?q=손익',false],['?category=dashboard&q=손익',false],['?category=invalid',true]]) {
  const current=boot(query);
  assert.equal(current.window.document.getElementById('kb-dashboard').hidden,!isDashboard,query);
  current.window.close();
}
console.log('PASS: direct URLs and old category/search links');
